version: '3.8' # Or the latest version you prefer

services:
  client:
    build: 
      context: ./client  # Build context is the client folder
      dockerfile: Dockerfile # Use Dockerfile if present, otherwise it's assumed
    ports:
      - "3000:3000" # Expose port 3000
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose port 5000
    depends_on:
      - client # Start the client before the server if needed
